### PR TITLE
Fix custom logo

### PR DESCRIPTION
**Pull request by kodypeterson**
Custom logos are not loading as /-/static/-/logo-sm is not the endpoint it is /-/logo-sm

### CODE REVIEW

**Comment by kodypeterson** [comment]
I will fix the tests....

**Comment by rlidwka** [comment]
Custom logo works fine for me. But it's probably because of `data-uri`. Which browser do you use? Does it support `background-image: url(data:image/png ...)`?

The fix isn't entirely correct, because people can override `/`. I mean, you can set up nginx to serve sinopia under `https://example.org/sinopia/`, in which case logo uri should be `https://example.org/sinopia/-/logo-sm`, not `https://example.org/-/logo-sm` like it will be with this fix.

Maybe replacing it with `../../-/logo-sm` would be better.

> I will fix the tests....

I believe tests aren't related to the PR, so don't bother. They probably changed something on Travis again.

**Comment by kodypeterson** [comment]
So, what if I were to add a baseURL in the config...

Also, this resolves setting a custom logo via the config. That was not working as the data-uri over-rode my  custom logo.

**Comment by kodypeterson** [comment]
So, re-reading your comment I guess we have a different idea of what custom logo is.

So, you have provided a way in the config for a user do define a location to a logo. This si the functionality that is not working. It always shows your npm logo. I had found it was due to the data-uri always overriding the background-image: url( /-/logo-sm );

Does this make more sense?

**Comment by rlidwka** [comment]
Okay, I see what you mean. I don't really know why custom logo was added, it came from a pull request 1.5 years ago.

Question: does someone really need a custom logo?

Maybe remove that option entirely, and let people who want to customize interface to supply a custom template file like it was suggested in https://github.com/rlidwka/sinopia/pull/208?

**Comment by kodypeterson** [comment]
Yeah either or. I know that our use case wants the support for custom logo.

**Comment by rlidwka** [comment]
Merged in https://github.com/rlidwka/sinopia/commit/bf40ceb064593a6b9b3485a7d9f6eb368aa36926 with a bunch of related fixes in https://github.com/rlidwka/sinopia/commit/d7c95d6cd6a62c16aa8c93ea1681dca32111c481 (since `/-/logo` is unused, I changed `/-/logo-sm` to `/-/logo` to avoid having dead code).

Thanks, and sorry for the delay.

**Comment by kodypeterson** [comment]
@rlidwka Cool, Thanks!

**Pull request closed without merging**
