### PR TITLE
Change _npmUser.name to author.name for entries

### LINKED ISSUE #173: _npmUser not sent with NPM 2.0.0
Hi,

When publishing packages with NPM 2.0.0 the _npmUser field is not set on the package. This leads to the user not showing up in the web interface.

### PR DESCRIPTION
**Pull request by kribblo**
Fixes #173 with missing author name in the web interface

### CODE REVIEW

**Comment by flawless2011** [comment]
+1

**Comment by mattfysh** [comment]
+1

**Comment by mathieumg** [comment]
+1

**Comment by gillesdemey** [comment]
Looks like a straight-forward change :+1:  

Some CI errors — possibly flaky tests?

**Comment by kribblo** [comment]
@gillesdemey yeah looked like some network errors on node 0.10 only and it was several days after the actual commit so not really sure what was up with that.

**Comment by thiago** [comment]
+1

**Comment by imfycc** [comment]
+1         I have encountered this problem can be solved this way

**Comment by kribblo** [comment]
Closing, it's been applied to active forks anyway

**Pull request closed without merging**
