### PR TITLE
only encode the / character to fix issue installing scoped packages f…

### PR DESCRIPTION
**Pull request by jameslnewell**
…rom an upstream registry. @see #278.

### CODE REVIEW

**Comment by jameslnewell** [comment]
Not sure if there's anything else that should actually should be encoded.

**Comment by rlidwka** [comment]
I'd consider it a bug in the npm registry that they encode some characters (`/`), but do not encode others (`@`). Maybe it should be reported there.

I'm fine with a workaround, but is it possible to encode all characters, and then decode `@` specifically for npm registry? Something like `encodeURIComponent(thing).replace(/^%40/, '@')`?

**Comment by iamstarkov** [comment]
@rlidwka @jameslnewell so is it going to be merged or, is there any already open issue in npm repo?

**Comment by iamstarkov** [comment]
Can we merge and publish this pull-request until changes will be made for npmjs?

**Comment by iamstarkov** [comment]
@rlidwka @jameslnewell it should be fixed in sinopia, or in npm. If think that this bug belong to npm, then can you create a bug report there?

**Comment by jameslnewell** [comment]
I'm keen for this PR to be merged, I don't imagine npm is likely to change their behaviour but I asked anyway in-case that's what is holding up this PR being merged.

Because the change is so small its pretty easy to patch if you want to use it in the mean-time.

**Comment by iamstarkov** [comment]
> Because the change is so small its pretty easy to patch if you want to use it in the mean-time.

also this patch can be easily removed, when npm will fix bug on their side

**Comment by jameslnewell** [comment]
Hi @rlidwka. @othiym23 has explained [here](https://github.com/npm/npm/issues/9351#issuecomment-136562160) that the behavior is by design. Can you please merge the PR? Ty :smiley:

**Comment by iamstarkov** [comment]
yay, its not a bug)

**Comment by rlidwka** [comment]
Merging. Thanks, and sorry for the delay.

**Comment by geovanisouza92** [comment]
It was released? I'm still having problems with scoped packages.

**Pull request merged**
