### PR TITLE
Support for downloading tarballs from authenticated upstream proxy

### PR DESCRIPTION
**Pull request by leaanthony**
The first commit adds support for pulling the package tarball from an authenticated upstream proxy. The second masks the username and password from the logs.

Fixes issue #134

### CODE REVIEW

**Comment by ghost** [comment]
+1 - I've verified this works would love to see it merged to master.

**Comment by robertgroh** [comment]
+1 - This works also for, me. Thanks @lea-anthony.

If this pull request is hold back, because of the trial-and-error commits (revert), then I would be glad to provide a clean pull request, which provides the functional commits via cherry-picking.

**Comment by anandgorantala** [comment]
@lea-anthony can you submit this PR to https://github.com/verdaccio/verdaccio. If you are busy, I will be happy to do it on your behalf

**Comment by leaanthony** [comment]
well, it's been a while. I hope you pulled it into verdaccio @ianand2

**Comment by juanpicado** [comment]
just fyi now we support `auth` field on each uplink (https://verdaccio.org/docs/en/uplinks#auth-property) based in Tokens.

**Pull request closed without merging**
