### PR TITLE
Deprecation notice

### PR DESCRIPTION
**Pull request by noamokman**
Added deprecation notice to the readme

Please merge this in to keep the project alive.

@rlidwka

### CODE REVIEW

**Comment by rsp** [comment]
@noamokman @rlidwka Any updates on the status of this PR?
(it's been almost a year since it was posted)

**Comment by grrowl** [comment]
Having tried verdaccio, then sinopia, and back to verdaccio, I am in strong support of this. It's a good fork, and even if this project is not officially depreciated it would be a disservice to users of either project to not link to it in the readme.

**Comment by juanpicado** [comment]
Hi, I think after one year contributing **verdaccio** I've been seen a lot of confusion, users that waste a lot of time trying with sinopia and they are not aware this project is **abandoned** and later on realize about several forks (sinopia2, verdaccio, etc ...) and somehow they end up using **verdaccio**. Sinopia is clearly leaking users, I see that every day. Please @rlidwka help your community approving this and stop this general confusion, keep this project open and with no deprecation notice is a security risk and just keep a lot of potential users bouncing asking themselves what the hack is happening. I love the work you have done and I think an action on your part 🙏  would be really helpful.  Refers to #376

**Comment by noamokman** [comment]
@rlidwka please just approve this , or give someone else access to the project.

**Review by eliotclarke — APPROVED** [review]
verdaccio has recent commits

**Pull request closed without merging**
