### PR TITLE
added cache_max_age option

### PR DESCRIPTION
**Pull request by dickeyxxx**
I'm trying to use sinopia behind a CDN

### CODE REVIEW

**Comment by rlidwka** [comment]
This conflicts with `no-cache` proposal in https://github.com/rlidwka/sinopia/pull/244.

What do you want CDN for? Is there a configuration option for that CDN to set a minimum max-age?

**Comment by dickeyxxx** [comment]
I'm using sinopia to deliver the CLI plugins for the Heroku toolbelt. We have users around the world and connecting to a US sinopia server can be really slow.

Adding the CDN has really helped (Cloudfront) but AWS only offers a minimum max-age. I patched with this change on the server and it's worked well for me.

I think there is room to modify this PR to add the no-cache header if the caching option isn't set. Thoughts?

**Comment by dickeyxxx** [comment]
I can fix the tests and add one too if you like the idea. There might be a way to add this more cleanly too if you have any ideas.

**Comment by dickeyxxx** [comment]
I'm not sure it conflicts actually. As I understand that middleware will let something else override later in the request chain.

Though personally I would rather be explicit about setting the header rather than relying on middleware in a separate dependency, but that's clearly a style decision on your part.

**Comment by dickeyxxx** [comment]
@rlidwka since my use-case is a little different than what most people need sinopia for, I ended up writing my own implementation https://github.com/dickeyxxx/elephant

**Comment by dickeyxxx** [comment]
thank you so much for making this project though! I used it in production for a while with great success.

**Pull request closed without merging**
