### PR TITLE
Update deps, make compile on Node v4 & 5

### PR DESCRIPTION
**Pull request by caseyWebb**
Used [updtr](https://github.com/peerigon/updtr) to update deps, and removed npm-shrinkwrap.json (I can regenerate this if need-be).

node-gyp doesn't complain (as much — no errors, only warnings) during install w/ node v4/5 now.

Note: I use [Greenkeeper](http://greenkeeper.io/) to make sure the deps in all my projects stay up to date; I highly recommend it.

### CODE REVIEW

**Comment by bestander** [comment]
closes #311

**Comment by bestander** [comment]
@rlidwka, this bug seems to block a lot of people and PR seems very small.
Any chance you could accept it?
Thanks.

**Comment by caseyWebb** [comment]
Let me double check and make sure this is all working. Locally it's good, but Travis appears to be failing.

**Comment by mima0815** [comment]
I don't know much about travis, but it seems to me that  travis does not have an C++11 Compiler available.

```
make: Entering directory `/home/travis/build/rlidwka/sinopia/node_modules/fs-ext/build'
  CXX(target) Release/obj.target/fs-ext/fs-ext.o
In file included from ../fs-ext.cc:27:0:
../../nan/nan.h:41:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /home/travis/.node-gyp/5.4.1/include/node/node.h:42:0,
```

Have a look here: [http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11](http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11)

The travis config has to be adapted also.

**Comment by landru29** [comment]
Waiting for the fix. The project is not usable as it is : impossible to install

**Comment by bestander** [comment]
I ended up using `npm pack` + `npm install <location on disk>` for my e2e tests.
Although that is just a tiny piece of what sinopia does it was good enough for me

**Pull request closed without merging**
